# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smallblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
